"""empty message

Revision ID: 48ed3eb1b7e0
Revises: 529b7e63c07f
Create Date: 2020-10-26 20:08:37.755769

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '48ed3eb1b7e0'
down_revision = '529b7e63c07f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('shop', 'shop_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shop', 'shop_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_table('category')
    # ### end Alembic commands ###
