"""empty message

Revision ID: 529b7e63c07f
Revises: 9e46425e43e2
Create Date: 2020-10-26 11:44:08.258938

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '529b7e63c07f'
down_revision = '9e46425e43e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_name', sa.String(length=32), nullable=False),
    sa.Column('price', sa.String(length=11), nullable=False),
    sa.Column('pic_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('price'),
    sa.UniqueConstraint('shop_name')
    )
    op.alter_column('team', 'avatar_url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('team', 'avatar_url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_table('shop')
    # ### end Alembic commands ###
