"""empty message

Revision ID: 9e46425e43e2
Revises: 3bbbd85fde8d
Create Date: 2020-10-23 09:04:38.539198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e46425e43e2'
down_revision = '3bbbd85fde8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_name', sa.String(length=32), nullable=False),
    sa.Column('member_mobile', sa.String(length=11), nullable=False),
    sa.Column('skill', sa.String(length=128), nullable=True),
    sa.Column('detail', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_mobile'),
    sa.UniqueConstraint('member_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team')
    # ### end Alembic commands ###
