"""empty message

Revision ID: aeb772e538cc
Revises: 48ed3eb1b7e0
Create Date: 2020-10-26 20:22:57.509504

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aeb772e538cc'
down_revision = '48ed3eb1b7e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('category_id', sa.Integer(), nullable=True))
    op.alter_column('shop', 'pic_url',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=255),
               nullable=True)
    op.create_foreign_key(None, 'shop', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shop', type_='foreignkey')
    op.alter_column('shop', 'pic_url',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=255),
               nullable=False)
    op.drop_column('shop', 'category_id')
    # ### end Alembic commands ###
